/**
 * ZALVY — Google Gemini AI Provider Adapter.
 *
 * Implements the `AIProvider` contract using Google Gemini REST & SSE APIs.
 * Supports model fallback, streaming responses, and embedding generation.
 *
 * @module lib/ai/gemini-adapter
 */

import type { AIProvider } from "./provider";
import type { AIMessage, AIProviderConfig, AIStreamChunk } from "@/types/ai";

export class GeminiProviderAdapter implements AIProvider {
  readonly providerId = "gemini";
  private defaultApiKey: string;
  private defaultModel: string;

  constructor(apiKey?: string, model = "gemini-2.5-flash") {
    this.defaultApiKey =
      apiKey ?? process.env.GOOGLE_GENAI_API_KEY ?? process.env.GEMINI_API_KEY ?? "";
    this.defaultModel = model;
  }

  private getApiKey(config?: AIProviderConfig): string {
    return config?.apiKey ?? this.defaultApiKey;
  }

  private getModel(config?: AIProviderConfig): string {
    return config?.model ?? this.defaultModel;
  }

  private formatContents(messages: AIMessage[]) {
    const contents: { role: string; parts: { text: string }[] }[] = [];
    let systemInstruction: { parts: { text: string }[] } | undefined;

    for (const msg of messages) {
      if (msg.role === "system") {
        systemInstruction = {
          parts: [{ text: msg.content }],
        };
      } else {
        contents.push({
          role: msg.role === "assistant" ? "model" : "user",
          parts: [{ text: msg.content }],
        });
      }
    }

    return { contents, systemInstruction };
  }

  async generateText(messages: AIMessage[], config?: AIProviderConfig): Promise<string> {
    const apiKey = this.getApiKey(config);
    if (!apiKey) {
      return "AI services are running in offline mode. Please configure GOOGLE_GENAI_API_KEY or OLLAMA_BASE_URL to enable live AI responses.";
    }

    const model = this.getModel(config);
    const { contents, systemInstruction } = this.formatContents(messages);

    const payload = {
      contents,
      ...(systemInstruction ? { systemInstruction } : {}),
      generationConfig: {
        temperature: config?.temperature ?? 0.7,
        maxOutputTokens: config?.maxTokens ?? 2048,
        topP: config?.topP ?? 0.95,
      },
    };

    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });

    if (!res.ok) {
      const errText = await res.text();
      throw new Error(`Gemini API error [${String(res.status)}]: ${errText}`);
    }

    const data = (await res.json()) as {
      candidates?: { content?: { parts?: { text?: string }[] } }[];
    };

    const answer = data.candidates?.[0]?.content?.parts?.[0]?.text;
    return answer ?? "No response generated by Gemini.";
  }

  async generateStream(
    messages: AIMessage[],
    config?: AIProviderConfig,
  ): Promise<ReadableStream<AIStreamChunk>> {
    const apiKey = this.getApiKey(config);
    const model = this.getModel(config);

    if (!apiKey) {
      return new ReadableStream<AIStreamChunk>({
        start(controller) {
          controller.enqueue({
            content:
              "AI Services running in fallback mode. Please supply a valid GOOGLE_GENAI_API_KEY or OLLAMA_BASE_URL in environment settings.",
            done: true,
          });
          controller.close();
        },
      });
    }

    const { contents, systemInstruction } = this.formatContents(messages);
    const payload = {
      contents,
      ...(systemInstruction ? { systemInstruction } : {}),
      generationConfig: {
        temperature: config?.temperature ?? 0.7,
        maxOutputTokens: config?.maxTokens ?? 2048,
        topP: config?.topP ?? 0.95,
      },
    };

    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:streamGenerateContent?key=${apiKey}&alt=sse`;

    const response = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });

    if (!response.ok || !response.body) {
      const errText = await response.text();
      throw new Error(`Gemini Stream API error [${String(response.status)}]: ${errText}`);
    }

    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = "";

    return new ReadableStream<AIStreamChunk>({
      async pull(controller) {
        const { done, value } = await reader.read();
        if (done) {
          controller.enqueue({ content: "", done: true, model });
          controller.close();
          return;
        }

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split("\n");
        buffer = lines.pop() ?? "";

        for (const line of lines) {
          const trimmed = line.trim();
          if (trimmed.startsWith("data: ")) {
            const jsonStr = trimmed.substring(6);
            if (jsonStr === "[DONE]") {
              controller.enqueue({ content: "", done: true, model });
              controller.close();
              return;
            }
            try {
              const parsed = JSON.parse(jsonStr) as {
                candidates?: { content?: { parts?: { text?: string }[] } }[];
              };
              const textSnippet = parsed.candidates?.[0]?.content?.parts?.[0]?.text;
              if (textSnippet) {
                controller.enqueue({ content: textSnippet, done: false, model });
              }
            } catch {
              // Ignore partial JSON parse errors
            }
          }
        }
      },
    });
  }

  async generateEmbedding(text: string): Promise<number[]> {
    const apiKey = this.defaultApiKey;
    if (!apiKey) return new Array<number>(768).fill(0);

    const url = `https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:embedContent?key=${apiKey}`;
    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "models/text-embedding-004",
        content: { parts: [{ text }] },
      }),
    });

    if (!res.ok) {
      return new Array<number>(768).fill(0);
    }

    const data = (await res.json()) as { embedding?: { values?: number[] } };
    return data.embedding?.values ?? new Array<number>(768).fill(0);
  }
}

export const defaultGeminiAdapter = new GeminiProviderAdapter();
