/**
 * ZALVY — Ollama AI Provider Adapter.
 *
 * Implements the `AIProvider` contract for local and hosted Ollama LLM instances.
 * Enables zero-cost local LLM execution, privacy-first processing, and multi-model deployment.
 *
 * @module lib/ai/ollama-adapter
 */

import type { AIProvider } from "./provider";
import type { AIMessage, AIProviderConfig, AIStreamChunk } from "@/types/ai";

export class OllamaProviderAdapter implements AIProvider {
  readonly providerId = "ollama";
  private baseUrl: string;
  private apiKey?: string;
  private defaultModel: string;

  constructor(
    baseUrl = process.env.OLLAMA_BASE_URL ?? "http://localhost:11434",
    apiKey = process.env.OLLAMA_API_KEY ?? "",
    defaultModel = process.env.OLLAMA_MODEL ?? "llama3",
  ) {
    this.baseUrl = baseUrl.replace(/\/$/, "");
    this.apiKey = apiKey;
    this.defaultModel = defaultModel;
  }

  private getHeaders(): Record<string, string> {
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
    };
    if (this.apiKey) {
      headers.Authorization = `Bearer ${this.apiKey}`;
    }
    return headers;
  }

  private formatMessages(messages: AIMessage[]) {
    return messages.map((msg) => ({
      role: msg.role,
      content: msg.content,
    }));
  }

  async generateText(messages: AIMessage[], config?: AIProviderConfig): Promise<string> {
    const model = config?.model ?? this.defaultModel;
    const url = `${config?.baseUrl ?? this.baseUrl}/api/chat`;

    const payload = {
      model,
      messages: this.formatMessages(messages),
      stream: false,
      options: {
        temperature: config?.temperature ?? 0.7,
        top_p: config?.topP ?? 0.9,
      },
    };

    try {
      const res = await fetch(url, {
        method: "POST",
        headers: this.getHeaders(),
        body: JSON.stringify(payload),
      });

      if (!res.ok) {
        const errText = await res.text();
        throw new Error(`Ollama API error [${String(res.status)}]: ${errText}`);
      }

      const data = (await res.json()) as { message?: { content?: string } };
      return data.message?.content ?? "No response generated by Ollama.";
    } catch (err) {
      return `Ollama connection failed: ${err instanceof Error ? err.message : String(err)}. Check if Ollama server is running.`;
    }
  }

  async generateStream(
    messages: AIMessage[],
    config?: AIProviderConfig,
  ): Promise<ReadableStream<AIStreamChunk>> {
    const model = config?.model ?? this.defaultModel;
    const url = `${config?.baseUrl ?? this.baseUrl}/api/chat`;

    const payload = {
      model,
      messages: this.formatMessages(messages),
      stream: true,
      options: {
        temperature: config?.temperature ?? 0.7,
        top_p: config?.topP ?? 0.9,
      },
    };

    try {
      const response = await fetch(url, {
        method: "POST",
        headers: this.getHeaders(),
        body: JSON.stringify(payload),
      });

      if (!response.ok || !response.body) {
        throw new Error(`Ollama stream error [${String(response.status)}]`);
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = "";

      return new ReadableStream<AIStreamChunk>({
        async pull(controller) {
          const { done, value } = await reader.read();
          if (done) {
            controller.enqueue({ content: "", done: true, model });
            controller.close();
            return;
          }

          buffer += decoder.decode(value, { stream: true });
          const lines = buffer.split("\n");
          buffer = lines.pop() ?? "";

          for (const line of lines) {
            const trimmed = line.trim();
            if (trimmed) {
              try {
                const parsed = JSON.parse(trimmed) as {
                  message?: { content?: string };
                  done?: boolean;
                };
                if (parsed.message?.content) {
                  controller.enqueue({
                    content: parsed.message.content,
                    done: parsed.done ?? false,
                    model,
                  });
                }
                if (parsed.done) {
                  controller.enqueue({ content: "", done: true, model });
                  controller.close();
                  return;
                }
              } catch {
                // Ignore chunk parse errors
              }
            }
          }
        },
      });
    } catch (err) {
      return new ReadableStream<AIStreamChunk>({
        start(controller) {
          controller.enqueue({
            content: `Ollama stream connection failed: ${err instanceof Error ? err.message : String(err)}`,
            done: true,
            model,
          });
          controller.close();
        },
      });
    }
  }

  async generateEmbedding(text: string): Promise<number[]> {
    const url = `${this.baseUrl}/api/embeddings`;
    try {
      const res = await fetch(url, {
        method: "POST",
        headers: this.getHeaders(),
        body: JSON.stringify({ model: this.defaultModel, prompt: text }),
      });
      if (!res.ok) return new Array<number>(768).fill(0);
      const data = (await res.json()) as { embedding?: number[] };
      return data.embedding ?? new Array<number>(768).fill(0);
    } catch {
      return new Array<number>(768).fill(0);
    }
  }
}

export const defaultOllamaAdapter = new OllamaProviderAdapter();
